export const useStyles = MUITheme => ({
  card: {
    minHeight: 440,
    width: 302,
    paddingTop: 10,
    marginBottom: 25,
    display: "inline-block",
    position: "relative",
    fontSize: 18,
    "&:hover": {
      backgroundColor: MUITheme.palette.background.mainContent,
      "& h4": { color: MUITheme.palette.primary.main },
      "& .MuiCardActions-spacing": { backgroundColor: MUITheme.palette.background.mainContent },
    },
  },
  cardHeader: {
    padding: "0 18px",
    alignItems: "flex-start",
    "& .MuiCardHeader-avatar": { marginRight: 0 },
    "& .MuiCardHeader-content": {
      textAlign: "left",
      marginLeft: 10,
    },
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 600,
    color: MUITheme.palette.text.darkGrey,
    letterSpacing: 0.23,
    lineHeight: "23px",
  },
  cardSubheader: {
    margin: 0,
    fontSize: 10,
    color: MUITheme.palette.text.lightGrey,
    fontWeight: 600,
    letterSpacing: 1.67,
    lineHeight: "16px",
    textTransform: "uppercase",
  },
  CardMedia: {
    height: 175,
    margin: "12px 0 17px",
  },
  cardContent: {
    padding: "0 18px",
    fontSize: 18,
    textAlign: "left",
  },
  cardTypograpy: {
    marginTop: 8,
    color: MUITheme.palette.text.primary,
    fontSize: 14,
    letterSpacing: 0.25,
    lineHeight: "21px",
  },
  cardActions: {
    boxSizing: "border-box",
    width: "100%",
    position: "absolute",
    bottom: 20,
    padding: "0 11px",
    justifyContent: "space-between",
    backgroundColor: MUITheme.palette.background.white,
    "& button": { padding: 0 },
  },
  showMore: {
    padding: 0,
    margin: 0,
    color: MUITheme.palette.text.lightGrey,
  },
  ratingStars: {
    "& label": { fontSize: 24 },
    "& .dv-star-rating-empty-star i": { color: '#ccc' },
  },
});
