export const organizationSetupStatuses = {
  ONBOARDING: "ONBOARDING",
  DRAFT: "DRAFT",
  VERIFY_APPROVED: "VERIFY_APPROVED",
  VERIFY_REJECTED: "VERIFY_REJECTED",
  PENDING_APPROVAL: "PENDING_APPROVAL",
  APPROVED: "APPROVED",
  BLOCKCHAIN_SUBMITTED: "BLOCKCHAIN_SUBMITTED",
  PUBLISHED: "PUBLISHED",
};
