export const clientTypes = {
  PUBLISHER_DAPP: "PUBLISHER_DAPP",
  MARKETPLACE_DAPP: "MARKETPLACE_DAPP",
  RFAI_DAPP: "RFAI_DAPP",
  STAKE_DAPP: "STAKE_DAPP",
};

export const clientTypesUtility = {
  PUBLISHER: "PUBLISHER",
  MARKETPLACE: "MARKETPLACE",
  RFAI: "RFAI",
  STAKE: "STAKE",
};
