export const useStyles = MUITheme => ({
  accountBalanceContainer: {
    paddingBottom: 40,
    borderRadius: 4,
    marginBottom: 30,
    backgroundColor: MUITheme.palette.background.white,
    boxShadow: "0 1px 1px 0 rgba(0,0,0,0.07), 0 2px 1px -1px rgba(0,0,0,0.07), 0 1px 3px 0 rgba(0,0,0,0.1)",
    flexBasis: "30%",
    "& h3": {
      padding: "0 22px",
      borderBottomWidth: 1,
      borderBottomStyle: "solid",
      borderBottomColor: MUITheme.palette.border.primary,
      margin: 0,
      color: MUITheme.palette.text.darkGrey,
      fontSize: 20,
      fontWeight: 400,
      lineHeight: "50px",
    },
    "@media(max-width:960px)": {
      maxWidth: "100%",
      marginTop: 25,
      marginLeft: 0,
      flexBasis: "100%",
    },
  },
  demo: { backgroundColor: "red" },
  warningBox: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: MUITheme.palette.border.warningBox,
    borderRadius: 4,
    padding: "13px 20px",
    margin: "28px 20px 0",
    backgroundColor: MUITheme.palette.background.warningBox,
    "& p, & span": {
      color: "rgba(0,0,0,0.6)",
      fontFamily: MUITheme.typography.fontFamily,
      fontSize: 14,
      lineHeight: "20px",
      letterSpacing: 0.25,
      textAlign: "left",
    },
    "& p": { paddingTop: 20 },
    "& a": {
      color: "#067AD7",
      fontWeight: "bold",
    },
  },
  btnContainer: {
    marginTop: 24,
    display: "flex",
    justifyContent: "center",
  },
});
